CREATE TABLE `contas` (
  `id` varchar(255) NOT NULL,
  `nome` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `login_email` varchar(255) DEFAULT NULL,
  `cpf_cnpj` varchar(20) DEFAULT NULL,
  `tipo_pessoa` varchar(20) DEFAULT NULL,
  `tipo_empresa` varchar(100) DEFAULT NULL,
  `nascimento` date DEFAULT NULL,
  `telefone` varchar(20) DEFAULT NULL,
  `celular` varchar(20) DEFAULT NULL,
  `endereco` varchar(255) DEFAULT NULL,
  `numero_endereco` varchar(20) DEFAULT NULL,
  `complemento` varchar(100) DEFAULT NULL,
  `bairro` varchar(100) DEFAULT NULL,
  `cep` varchar(15) DEFAULT NULL,
  `cidade_id` varchar(100) DEFAULT NULL,
  `estado` varchar(50) DEFAULT NULL,
  `pais` varchar(50) DEFAULT NULL,
  `site` varchar(255) DEFAULT NULL,
  `wallet_id` varchar(255) DEFAULT NULL,
  `api_key` varchar(255) DEFAULT NULL,
  `agencia` varchar(20) DEFAULT NULL,
  `conta_numero` varchar(20) DEFAULT NULL,
  `digito_conta` varchar(5) DEFAULT NULL,
  `renda` decimal(12,2) DEFAULT NULL,
  `senha` varchar(255) DEFAULT NULL,
  `data_cadastro` datetime DEFAULT CURRENT_TIMESTAMP,
  `asaas_customer_id` varchar(100) DEFAULT NULL,
  `status` varchar(20) DEFAULT 'pendente',
  `documentos_enviados` tinyint(1) DEFAULT '0',
  `api_id` varchar(100) DEFAULT NULL,
  `asaas_pix_id` varchar(100) DEFAULT NULL COMMENT 'ID do PIX no Asaas',
  `asaas_pix_key` varchar(255) DEFAULT NULL COMMENT 'Chave PIX cadastrada',
  `asaas_pix_payload` text COMMENT 'Payload PIX para transações',
  `asaas_pix_qrcode` longtext COMMENT 'QR Code PIX em base64',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
